"""Re-export shim — entity database now lives in the corp-entity-db package."""

from corp_entity_db import *  # noqa: F401, F403
from corp_entity_db import (
    CompanyRecord,
    CompanyMatch,
    DatabaseStats,
    OrganizationDatabase,
    CompanyDatabase,
    get_database,
    PersonRecord,
    PersonMatch,
    PersonType,
    PersonDatabase,
    get_person_database,
    CompanyEmbedder,
    get_embedder,
    download_database,
    get_database_path,
    upload_database,
    upload_database_with_variants,
    OrganizationResolver,
    get_organization_resolver,
)

__all__ = [
    "CompanyRecord",
    "CompanyMatch",
    "DatabaseStats",
    "OrganizationDatabase",
    "CompanyDatabase",
    "get_database",
    "PersonRecord",
    "PersonMatch",
    "PersonType",
    "PersonDatabase",
    "get_person_database",
    "CompanyEmbedder",
    "get_embedder",
    "download_database",
    "get_database_path",
    "upload_database",
    "upload_database_with_variants",
    "OrganizationResolver",
    "get_organization_resolver",
]
